services:
  - type: web
    name: dk-mart
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
